### ISSUE TITLE
[joss review] improve citation for which the admm algorithms are based upon

### ISSUE THREAD

**Issue by mirca** [carnotresearch/cr-sparse#23]
I feel that the following reference should be more visible in the online documentation: https://github.com/carnotresearch/cr-sparse/blob/4247e0445b7a4b8be846c1d370adcad3c0484f0a/src/cr/sparse/_src/cvx/adm/yall1.py#L16

In addition, please use the full reference for the paper, i.e., add author names, journal, year, vol, etc.

**Comment by shailesh1729** [comment]
Thanks for pointing it out. Have added it in the API docs: https://cr-sparse.readthedocs.io/en/latest/source/cvx_recovery.html#alternating-directions-methods 

as well as the function and module [docstrings](https://github.com/carnotresearch/cr-sparse/commit/db56a12d3b250ba7b3c23d8bd72c5d8d0a1d1cbe).
