### ISSUE TITLE
[joss review] comments on the manuscript writing

### ISSUE THREAD

**Issue by mirca** [carnotresearch/cr-sparse#24]
- [x] I wouldn't use attributive adjective such as "decent", as you used, in line 75 to describe the implementation in ``aaren/wavelets``, or "old" in lines 76, 83.

- [x] I think subjective claims, e.g., line 131 "we believe that our implementation is cleaner and simpler...", should not be included in the paper.

**Comment by shailesh1729** [comment]
Have corrected the paper by revising/removing the lines.
