### ISSUE TITLE
Random orthogonal matrices have non-uniform distribution

### ISSUE THREAD

**Issue by RauliRuohonen** [carnotresearch/cr-sparse#28]
Consider this code:

```
import cr.sparse.data
import cr.sparse.lop
import jax.random
import jax.numpy as jnp
import matplotlib.pyplot as plt
import numpy as np

def to_array(op):
    return np.asarray(cr.sparse.lop.to_matrix(op))

def rand_orth_ref(key, n):
    Q, R = jnp.linalg.qr(jax.random.normal(key, (n, n)))
    return Q * jnp.sign(jnp.diag(R))  # this multiplication is important

def rand_orth_nonuniform(key, n):
    Q, R = jnp.linalg.qr(jax.random.normal(key, (n, n)))
    return Q

def rand_orth_nonuniform2(key, n):
    Q = rand_orth_ref(key, n)
    if Q[0, 0] > 0:
        Q = -Q  # Pretend the QR implementation returned -Q, -R instead (which it is allowed to do)
    return Q

def rand_orth_rows_dict(key, n):
    return to_array(cr.sparse.lop.random_orthonormal_rows_dict(key, n, n))

def rand_orth_onb_dict(key, n):
    return to_array(cr.sparse.lop.random_onb_dict(key, n))

def rand_orth_subspaces(key, n):
    Q, = cr.sparse.data.random_subspaces(key, n, n, 1)
    return np.asarray(Q)

def uniform_random(n, rand_orth):
    Qs = [rand_orth(key, 2) for key in jax.random.split(jax.random.PRNGKey(0), n)]
    xs, ys = np.array([Q[0] for Q in Qs]).T
    return np.arctan2(ys, xs) / (2 * np.pi) + .5

# ANGLES = uniform_random(10_000, rand_orth_ref)
# ANGLES = uniform_random(10_000, rand_orth_nonuniform)
# ANGLES = uniform_random(10_000, rand_orth_nonuniform2)
# ANGLES = uniform_random(10_000, rand_orth_rows_dict)
# ANGLES = uniform_random(10_000, rand_orth_onb_dict)
ANGLES = uniform_random(10_000, rand_orth_subspaces)

assert ANGLES.min() >= 0 and ANGLES.max() <= 1
print(ANGLES[ANGLES < .5].max(), ANGLES[ANGLES > .5].min())  # both should be close to 0.5
plt.hist(ANGLES, bins=20)
plt.xlim(0, 1);
```

All of the ways to generate `ANGLES` except for `rand_orth_ref()` are obviously non-uniform at least on my machine (the exact implementation of the QR decomposition generally depends on the system, but I don't know about JAX specifically). The print statement produces a result close to [0.25, 0.75] for me, i.e. in 2d half of the angles are never produced for the first basis vector.

The root cause is e.g. [this code](https://github.com/carnotresearch/cr-sparse/blob/61081e90aaf992a53b04782c7f40c595f7a31642/src/cr/sparse/_src/data/synthetic/subspaces.py#L39), which essentially implements sampling using the method `rand_orth_nonuniform()` above. The code is clearly intended to produce uniformly random samples, but it is missing the correction for signs as in `rand_orth_ref()`, which leaves the distribution dependent on how the QR decomposition happens to choose the arbitrary signs of the diagonal of `R`. Basically, `QR = Q'R'` where `Q' = QD`, `R' = DR` and `D` is any diagonal matrix with ±1 entries on the diagonal, and you can produce a non-uniform distribution by choosing `D` suitably, as in the `rand_orth_nonuniform2()` example. The choice of `D` is implementation-defined and hence arbitrary. The sign correction is mentioned e.g. in [this Wikipedia article](https://en.wikipedia.org/wiki/Orthogonal_matrix#Randomization), which cites a Notices of the AMS article that goes into detail on the issue.

There are other places in the code using QR decomposition in the same way, at least [here](https://github.com/carnotresearch/cr-sparse/blob/61081e90aaf992a53b04782c7f40c595f7a31642/src/cr/sparse/_src/dict/simple.py#L157) and [here](https://github.com/carnotresearch/cr-sparse/blob/61081e90aaf992a53b04782c7f40c595f7a31642/src/cr/sparse/_src/dict/simple.py#L131).

**Comment by shailesh1729** [comment]
Thanks for the bug report. I will try to resolve it as soon as possible.

**Comment by shailesh1729** [comment]
@RauliRuohonen , thank you for your insightful suggestions and my sincere apologies for the extremely delayed response. I have tried some changes in the dev branch [here](https://github.com/carnotresearch/cr-sparse/blob/7cff50221086ae08798b84c9ed029b39669b37df/src/cr/sparse/_src/data/synthetic/subspaces.py#L44).

```python
        key = keys[i]
        k1, k2 = random.split(key)
        A = random.normal(k1, [N, D])
        Q, _ = jnp.linalg.qr(A)
        dg = 2 * random.bernoulli(k2, shape=(D,)) - 1
        # apply the random sign changes
        Q = cnb.diag_postmultiply(Q, dg)
````
This is leading to the following histogram from your sample code:

![image](https://user-images.githubusercontent.com/8783308/185492515-bb3afffa-39a4-419f-92f9-e69e27c3ecff.png)

I guess this looks reasonably uniform now.  I once again really appreciate your time spent reviewing this work and identifying a critical bug. 

I will correct the issue in the remaining places also as suggested.

**Comment by shailesh1729** [comment]
Have fixed `random_onb` and `random_orthonormal_rows` functions also.  Picking the sign bit from the diagonal entries of R also works fine as suggested by you.  Please note that the fixes are still in the [dev](https://github.com/carnotresearch/cr-sparse/tree/dev) branch.
